### ISSUE TITLE
bug: ECS Integration failing with "Request failed with status 500 Tasks cannot be empty."

### ISSUE THREAD

**Issue by bharling** [awslabs/backstage-plugins-for-aws#140]
### 📜 Description

We've setup the ECS plugin in our backstage installation and have orchestrated cross-account access and discovery using the resource tagging API. We're seeing data for a few of our services, but a lot of them report the following error when navigating to the ECS tab in the service entity page

```json
{
    "$fault": "client",
    "$metadata": {
        "attempts": 1,
        "httpStatusCode": 400,
        "requestId": "c871f2f3-c5d8-4cfa-9506-2a7f083947ba",
        "totalRetryDelay": 0
    },
    "__type": "InvalidParameterException",
    "level": "error",
    "message": "Request failed with status 500 Tasks cannot be empty.",
    "name": "InvalidParameterException",
    "service": "backstage",
    "stack": "InvalidParameterException: Tasks cannot be empty.\n at de_InvalidParameterExceptionRes (/app/node_modules/@aws-sdk/client-ecs/dist-cjs/index.js:2367:21)\n at de_CommandError (/app/node_modules/@aws-sdk/client-ecs/dist-cjs/index.js:2201:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n at async /app/node_modules/@smithy/core/dist-cjs/index.js:165:18\n at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n at async DefaultAmazonEcsService.getServices (/app/node_modules/@aws/amazon-ecs-plugin-for-backstage-backend/dist/index.cjs.js:126:37)\n at async /app/node_modules/@aws/amazon-ecs-plugin-for-backstage-backend/dist/index.cjs.js:89:16\n at async Promise.all (index 0)\n at async DefaultAmazonEcsService.getServicesByEntity (/app/node_modules/@aws/amazon-ecs-plugin-for-backstage-backend/dist/index.cjs.js:85:22)\n at async /app/node_modules/@aws/amazon-ecs-plugin-for-backstage-backend/dist/index.cjs.js:177:24",
    "type": "errorHandler"
}
```

I've confirmed that the service is running in the expected cluster and has 2 fargate tasks placed and healthy. For some other services in our catalog (running in the same cluster) we do see the expected ECS information correctly rendered.

### 👍 Expected behavior

Service information should be visible in the ECS Tab

### 👎 Actual Behavior with Screenshots

![image](https://github.com/awslabs/backstage-plugins-for-aws/assets/1139376/8bde7cf1-b65f-4cec-b3c9-ad0b668baef7)

### 👟 Reproduction steps

Followed ECS integration setup guide, setup cross account access using resource tagging API as per documentation.

### 🖥️ Your Environment

```
yarn run v1.22.19
$ /Users/ben.harling/co/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/arm64
node: v20.9.0
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.26.3

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.0, 0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.18, 0.6.17
  @backstage/backend-tasks                                         0.5.22, 0.5.23
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.5, 1.6.4
  @backstage/catalog-model                                         1.4.5, 1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.4, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0, 1.11.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12, 0.4.13
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.0, 1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-pagerduty                                      0.7.7
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28, 0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.22
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.89s.
```

**Comment by mdb** [comment]
I believe this occurs because empty tasks are passed here, somehow:

https://github.com/awslabs/backstage-plugins-for-aws/blob/main/plugins/ecs/backend/src/service/DefaultAmazonEcsService.ts#L211

**Comment by niallthomson** [comment]
Thanks for reporting, I'll take a look in to this.

**Comment by bharling** [comment]
We think this could potentially be a product of some funky ecs service resource tagging on our part, however it feels like the plugin might want to catch an error like this an fail gracefully somehow too

**Comment by niallthomson** [comment]
I've found a couple of places where the handling can be improved, I'm working on a fix.

**Comment by niallthomson** [comment]
Just released updated packages which may resolve this. If it doesn't then we'll need to get more diagnostic information.

**Comment by bharling** [comment]
Many thanks - we'll take a look!

**Comment by niallthomson** [comment]
@bharling were you able to verify if the fixes have resolved this issue?

**Comment by niallthomson** [comment]
Closing this for now, would welcome any further reports
